<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

// Permissions.
define('ISLANDORA_ARCHIVESPACE_API', 'archivespace rest api');

// Menu items.
define('ISLANDORA_ARCHIVESPACE_REST_VERSION', 'v1');
define('ISLANDORA_ARCHIVESPACE_REST_URL_PREFIX', 'islandora/archivesspace/' . ISLANDORA_ARCHIVESPACE_REST_VERSION);
define('ISLANDORA_ARCHIVESPACE_REST_ENDPOINT_MENU', ISLANDORA_ARCHIVESPACE_REST_URL_PREFIX . '/update');

/**
 * Implements hook_permission().
 */
function islandora_archivespace_permission() {
  return array(
    ISLANDORA_ARCHIVESPACE_API => array(
      'title' => t('Access Archivespace REST Api'),
      'description' => t('Allows user to update objects through Archivespace REST API.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_archivespace_menu() {
  $items = array();
  $items['admin/islandora/archivespace'] = array(
    'title' => 'Islandora Archivespace',
    'description' => 'Configure settings for Islandora Archivespace integration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_archivespace_admin_form'),
    'file' => 'includes/admin.form.inc',
    'access arguments' => array('administer site configuration'),
  );

  $items[ISLANDORA_ARCHIVESPACE_REST_ENDPOINT_MENU] = array(
    'page callback' => 'islandora_archivespace_rest',
    'file' => 'includes/utilities.inc',
    'access arguments' => array(ISLANDORA_ARCHIVESPACE_API),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_islandora_ingest_steps()
 */
function islandora_archivespace_islandora_ingest_steps(array $form_state) {
  $shared_storage = islandora_ingest_form_get_shared_storage($form_state);
  $intersection = array_intersect($shared_storage['models'], variable_get('islandora_archivespace_enabled_models', array()));
  if(count($intersection) > 0) {
    return array(
      'islandora_archivespace_step_enable_form' => array(
        'type' => 'form',
        'weight' => -5,
        'form_id' => 'islandora_archivespace_step_enable_form',
        'file' => 'includes/ingest_steps.inc',
        'module' => 'islandora_archivespace',
      ),
    );
  }
}

/**
 * Implements hook_islandora_ingest_steps_alter().
 */
function islandora_archivespace_islandora_ingest_steps_alter(array &$steps, array &$form_state) {
  if(!isset($form_state['islandora']['step_storage']['islandora_archivespace_step_enable_form']['islandora_archivespace_enable'])){
    return;
  }

  $enabled = $form_state['islandora']['step_storage']['islandora_archivespace_step_enable_form']['islandora_archivespace_enable'];
  if($enabled) {
    // Don't use the normal MODs form.
    if(isset($steps['xml_form_builder_metadata_step']) && $steps['xml_form_builder_metadata_step']['args'][0]['dsid'] == 'MODS') {
      unset($steps['xml_form_builder_metadata_step']);
    }

    // Don't use the normal form association selector.
    if(isset($steps['xml_form_builder_association_step'])) {
      unset($steps['xml_form_builder_association_step']);
    }

    // Do add a basic metadata form for the archivespace ingest.
    $steps['islandora_archivespace_step_metadata_form'] = array(
      'type' => 'form',
      'weight' => -4,
      'form_id' => 'islandora_archivespace_step_metadata_form',
      'file' => 'includes/ingest_steps.inc',
      'module' => 'islandora_archivespace',
    );
  }
}
